#GET
GET http://localhost:8087/api/v1/agendamento/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/agendamento
Content-Type: application/json

{
    "data":"2023-05-19",
    "id_tipo_servico":1,
    "status":"Pendente",
    "id_veiculo":2
}
###

#PUT
PUT http://localhost:8087/api/v1/agendamento
Content-Type: application/json

{
    "id_agendamento":4,
    "data":"2023-05-19",
    "id_tipo_servico":1,
    "status":"Aprovado",
    "id_veiculo":2
}
###

#PATCH
PATCH http://localhost:8087/api/v1/agendamento
Content-Type: application/json

{
    "id_agendamento":4,
    "status":"Aprovado"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/agendamento/5
Content-Type: application/json