#GET
GET http://localhost:8087/api/v1/produto/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/produto
Content-Type: application/json

{
    "id_agenda":2,
    "descricao":"Pneu"
    
}
###

#PUT
PUT http://localhost:8087/api/v1/produto
Content-Type: application/json

{
    "id_produto":1,
    "id_agenda":4,
    "descricao":"Pneu"
}
###

#PATCH
PATCH http://localhost:8087/api/v1/produto
Content-Type: application/json

{
    "id_produto":1,
    "descricao":"Pneus"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/produto/4  
Content-Type: application/json