#GET
GET http://localhost:8087/api/v1/tipo_servico/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/tipo_servico
Content-Type: application/json

{
    "nome":"Lanternagem",
    "imagem":"imagens/a.jpeg",
    "descricao":"Conserto de lataria"
}
###

#PUT
PUT http://localhost:8087/api/v1/tipo_servico
Content-Type: application/json

{
    "id_tipo_servico":1,
    "nome":"Lanternagemm",
    "imagem":"imagens/a.jpeg",
    "descricao":"Conserto de lataria"
}
###

#PATCH
PATCH http://localhost:8087/api/v1/tipo_servico
Content-Type: application/json

{
    "id_tipo_servico":1,
    "nome":"Lanternagemm"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/tipo_servico/1
Content-Type: application/json