#GET
GET http://localhost:8087/api/v1/agenda/2/servico
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/agenda/2/servico
Content-Type: application/json

{
    "id":3,
    "id_agenda":2,
    "observacao":"a"
}
###

#PUT / NOT SUPORTED
PUT http://localhost:8087/api/v1/agenda/2/servico
Content-Type: application/json

{
    "id_agenda":2,
    "id_servico":1,
    "observacao":"a"
}
###

#PATCH / NOT SUPORTED
PATCH http://localhost:8087/api/v1/agenda/1/servico
Content-Type: application/json

{
    "observacao":""
}
###

#DELETE
DELETE http://localhost:8087/api/v1/agenda/2/servico/3
Content-Type: application/json