#GET
GET http://localhost:8087/api/v1/regra_funcionamento/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/regra_funcionamento
Content-Type: application/json

{
    "dias":"01",
    "hr_inicio":"10:20",
    "hr_termino":"18:30"
}
###

#PUT
PUT http://localhost:8087/api/v1/regra_funcionamento
Content-Type: application/json

{
    "id":1,
    "dias":"01",
    "hr_inicio":"11:20",
    "hr_termino":"12:30"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/regra_funcionamento/2
Content-Type: application/json