#GET
GET http://localhost:8087/api/v1/regra_funcionamento/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/regra_funcionamento
Content-Type: application/json

{
    "dias":"01",
    "hr_inicio":"2023-09-28T15:00:00.000+00:00",
    "hr_termino":"2023-09-28T15:00:00.000+00:00"
}
###

#PUT
PUT http://localhost:8087/api/v1/regra_funcionamento
Content-Type: application/json

{
    "id":1,
    "dias":"011",
    "hr_inicio":"",
    "hr_termino":""
}
###

#DELETE
DELETE http://localhost:8087/api/v1/regra_funcionamento/2
Content-Type: application/json