#GET
GET http://localhost:8087/api/v1/usuario/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "nome":"Gabriel"    ,
    "cpf":"111.111.111-12",
    "email":"gab@gmail.com",
    "telefone":"2222222222",
    "senha":"123",
    "permission":"Cliente"
}
###

#PUT
PUT http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "id":1,
    "nome":"Gustiavin",
    "cpf":"050.189.540-00",
    "email":"gustavo@gmail.com",
    "telefone":"11111111111",
    "senha":123,
    "permission":"Cliente"
}
###

#PATCH
PATCH http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "id_usuario":2,
    "nome":"Guilherme Campos"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/usuario/1
Content-Type: application/json