#GET
GET http://localhost:8087/api/v1/usuario/
Content-Type: application/json
###

#GET
GET http://localhost:8087/api/v1/usuario/email/sasa/exists
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "nome":"Yuri",
    "cpf":"111.111.111-33",
    "email":"y@y",
    "telefone":"2222222222",
    "senha":"123",
    "permission":"Funcionario"
}
###

#PUT
PUT http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    
    "id": 2,
    "nome": "Gabriel",
    "cpf": "11111111111",
    "email": "gabrielspdev@gmail.com",
    "telefone": "(11) 11111-1111",
    "permission": "Admin",
    "senha":"123"
  
}
###

#PATCH
PATCH http://localhost:8087/api/v1/usuario
Content-Type: application/json

{
    "id_usuario":2,
    "nome":"Guilherme Campos"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/usuario/11
Content-Type: application/json