#GET
GET http://localhost:8087/api/v1/veiculo/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/veiculo
Content-Type: application/json

{
    "placa":"CCB-222",
    "modelo":"Mustang",
    "tipo":"Carro", 
    "id_cliente":2
}
###

#PUT
PUT http://localhost:8087/api/v1/veiculo
Content-Type: application/json

{
    "id":1,
    "placa":"CCB-222",
    "modelo":"Mustang",
    "tipo":"Carro", 
    "id_cliente":1
}
###

#PATCH
PATCH http://localhost:8087/api/v1/veiculo
Content-Type: application/json

{
    "id_veiculo":2,
    "modelo":"Honda HRV"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/veiculo/4
Content-Type: application/json