#GET
GET http://localhost:8087/api/v1/agenda/
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/agenda
Content-Type: application/json

{
    "id_horario":1,
    "id_veiculo":6,
    "status":"Pendente",
    "dt_previsao":"",
    "dt_fim":"",
    "observacao":""
    
}
###

#PUT
PUT http://localhost:8087/api/v1/agenda
Content-Type: application/json

{
    "id_agenda":6,
    "id_horario":1,
    "id_veiculo":1,
    "status":"Pendente",
    "dt_previsao":"2023-05-19",
    "dt_fim":"2023-05-19",
    "observacao":"a"
}
###

#PATCH
PATCH http://localhost:8087/api/v1/agenda
Content-Type: application/json

{
    "id_agenda":1,
    "status":"Aprovado"
}
###

#DELETE
DELETE http://localhost:8087/api/v1/agenda/5
Content-Type: application/json